input:
  stdin: {}

pipeline:
  processors:
    - mapping: |
        root.doc = this
        root.first_name = this.names.index(0).uppercase()
        root.last_name = this.names.index(-1).hash("sha256").encode("base64")

output:
  file:
    path: /home/jayasudha/Desktop/learning-bento/output.txt
